# 3- Ağırlık Ortalama Kaydırma Kümelemesi:

##### Ortalama kaydırma kümeleme, veri noktalarının yoğun alanlarını bulmaya çalışan kayan pencere tabanlı bir algoritmadır. Centroid tabanlı bir algoritmadır, yani amacın her bir grubun / sınıfın merkez noktalarını bulmaktır, bu da kayan pencere içindeki noktaların ortalaması olacak merkez noktaları için adayları güncelleyerek çalışır. Bu aday pencereler daha sonra, neredeyse kopyaları ortadan kaldırmak için bir işlem sonrası aşamasında filtrelenir ve nihai merkez noktaları ve bunlara karşılık gelen grupları oluşturur.

##### Sürgülü pencerelerin tümü ile uçtan uca tüm sürecin bir örneği aşağıda gösterilmiştir. Her siyah nokta, kayan bir pencerenin merkezini temsil eder ve her gri nokta bir veri noktasıdır.

![Ekran görüntüsü 2024-05-17 070257](https://github.com/ahmettsimsek/Makine-Ogrenmesi-Temelleri/assets/124433579/6bab6809-aac5-409d-ab0d-424ca998b13f)


1) Ortalama-kaymayı açıklamak için, yukarıdaki resimde olduğu gibi iki boyutlu uzayda
bir dizi noktayı ele alacağız. Bir C noktasında ortalanmış (rastgele seçilmiş) ve
çekirdek olarak r yarıçapına sahip dairesel bir kayan pencere ile başlıyoruz.

2) Her yinelemede, kayan pencere, merkez noktası pencere içindeki noktaların
ortalamasına kaydırılarak (dolayısıyla adı) daha yüksek yoğunluklu bölgelere
kaydırılır. Sürgülü pencere içindeki yoğunluk, içindeki noktaların sayısı ile orantılıdır.


3) Bir kaymanın çekirdek içinde daha fazla noktayı barındırabileceği bir yön olmayana
kadar ortalamaya göre kayan pencereyi kaydırmaya devam ediyoruz. Yukarıdaki
grafiğe bakın; Artık yoğunluğu artırmayana kadar (yani penceredeki nokta sayısı)
daireyi hareket ettirmeye devam ediyoruz.

4) 1'den 3'e kadar olan bu adım süreci, tüm noktalar bir pencerenin içinde kalana kadar
birçok sürgülü pencerede yapılır. Birden çok sürgülü pencere örtüştüğünde, en çok
noktayı içeren pencere korunur. Veri noktaları daha sonra bulundukları kayan
pencereye göre kümelenir.

---------

Mean-Shift algoritmasının nasıl çalıştığını anlamak için basit bir örnek. Bu örnekte, önce 4 farklı blob içeren 2D veri seti oluşturacağız ve ardından sonucu görmek için Mean-Shift algoritmasını uygulayacağız.

In [ ]:
%matplotlib inline
import numpy as np
from sklearn.cluster import MeanShift
import matplotlib.pyplot as plt
from matplotlib import style
style.use("ggplot")
from sklearn.datasets.samples_generator import make_blobs
centers = [[3,3,3],[4,5,5],[3,10,10]]
X, _ = make_blobs(n_samples = 700, centers = centers, cluster_std = 0.5)
plt.scatter(X[:,0],X[:,1])
plt.show()

![Ekran görüntüsü 2024-05-17 070550](https://github.com/ahmettsimsek/Makine-Ogrenmesi-Temelleri/assets/124433579/ca7360a0-805f-4ff5-9a48-26b646d120e5)


In [ ]:
ms = MeanShift()
ms.fit(X)
labels = ms.labels_
cluster_centers = ms.cluster_centers_
print(cluster_centers)
n_clusters_ = len(np.unique(labels))
print("Estimated clusters:", n_clusters_)
colors = 10*['r.','g.','b.','c.','k.','y.','m.']
for i in range(len(X)):
    plt.plot(X[i][0], X[i][1], colors[labels[i]], markersize = 3)
plt.scatter(cluster_centers[:,0],cluster_centers[:,1],
    marker=".",color='k', s=20, linewidths = 5, zorder=10)
plt.show()

#### Çıktı

In [ ]:
[[ 2.98462798 9.9733794 10.02629344]
[ 3.94758484 4.99122771 4.99349433]
[ 3.00788996 3.03851268 2.99183033]]
Estimated clusters: 3

![Ekran görüntüsü 2024-05-17 070648](https://github.com/ahmettsimsek/Makine-Ogrenmesi-Temelleri/assets/124433579/22c5c757-26dd-4c39-9ba9-e8ba7c3f5bdd)


-------

Ağırlık Ortalama Kaydırma Kümelemes  konusunda daha fazla detaya ulaşmak için, benim de örnek için Yararlandığım "TRPOST" sayfasına aşağıdaki linkten ulaşabilirsiniz:

https://post.nghiatu.com/tr/tutorial/machine-learning-with-python/clustering-algorithms-mean-shift-algorithm/kumeleme-algoritmalari-ortalama-kayma-algoritmasi